//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BizPhoneManager.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_DLG_ABOUTBOX                100
#define IDS_ABOUTBOX                    101
#define IDD_BIZPHONE_SEETING_SHEET      102
#define IDS_DLG_COMMON_CLOSE            103
#define IDS_DLG_COMMON_SAVE             104
#define IDS_PAGE_IMPORT_LOCAL_MOBILE    105
#define IDD_SELCOMPORT                  106
#define IDS_PAGE_EXPORT_LOCAL_MOBILE    106
#define IDD_INPUT_PASS                  107
#define IDS_PAGE_CHANGE_PWD             107
#define IDD_DLG_INPUTPWD                107
#define IDS_PAGE_CHANGE_PWD_AND_DOWNLOAD 108
#define IDS_PAGE_CHANGE_PWD_DOWN_DEFAULT 109
#define IDS_PAGE_IMPORT_ALLDATA         110
#define IDS_PAGE_EXPORT_ALLDATA         111
#define IDS_PAGE_LOAD_SETTING           112
#define IDS_PAGE_SAVE_SETTING           113
#define IDS_PAGE_SAVE_DEFAULT           114
#define IDS_PAGE_RECORVER_DEFAULT       115
#define IDR_MAINFRAME                   128
#define IDS_APPNAME                     128
#define IDD_PROPPAGE_B_PWD              140
#define IDI_ICON1                       142
#define IDB_LOGO                        143
#define IDB_FLASH                       144
#define IDD_WAIT_DIALOG                 145
#define IDR_GIF_LOGO                    147
#define IDR_JPG_SPLASH                  153
#define IDD_DLG_SERIAL                  161
#define IDR_LABLE1                      176
#define IDB_BITMAP1                     177
#define IDB_BITMAP_PG530CONTENT         177
#define IDD_PACKING_SELETE_DLG          178
#define IDD_ATTRIBUTE_RECT              183
#define IDD_PG530_IMEI                  184
#define IDD_ATTRIBUTE_RECT1             185
#define IDD_PG530_CARTONBOX             185
#define IDD_PHONE_ABSOLUTED_PACK        186
#define IDC_PAGE_B_EDIT_CNFPWD          1003
#define IDC_COMPORT                     1007
#define IDC_COMBATU                     1008
#define IDC_OLDPASS                     1012
#define IDC_PAGE_9_RADIO_LOCKREGION     1012
#define IDC_SETTING_CTRL_TREE           1018
#define IDC_PAGE_9_RADIO_SHIELDREGION   1018
#define IDC_SETTING_SHEET_PLACEHOLDER   1019
#define ID_SETTING_SHEET_BTN_SAVE       1020
#define ID_SETTING_SHEET_BTN_EXIT       1021
#define ID_SETTING_SHEET_BTN_EXIT2      1022
#define ID_SETTING_SHEET_BTN_LOCK       1022
#define IDC_CURRENT_STATUS              1058
#define IDC_MSG_DLG_EDIT_TASK           1061
#define IDC_PIC_GIF_LOGO                1064
#define IDC_PAGE_X_LIST_OUTPUT          1066
#define IDC_PAGE_X_REPORT_OUTPUT        1088
#define IDC_ABOUTDLG_VERSION            1097
#define IDC_CUSTOM                      1185
#define IDC_SERIAL                      1186
#define IDC_CK_PIN_AOTULOCK             1239
#define IDC_STATIC_PIN_AOTULOCK         1240
#define IDC_RADIO_PIN_AOTULOCK_YES      1241
#define IDC_CK_PIN_INITCODE             1242
#define IDC_RADIO_PIN_AOTULOCK_NO       1243
#define IDC_EDIT_PIN_INIT               1244
#define IDC_STATIC_PIN_RANDOM           1245
#define IDC_RADIO_PIN_RANDOM_YES        1246
#define IDC_RADIO_PIN_RANDOM_NO         1247
#define IDC_EDIT_PIN_FIXEDCONDE         1248
#define IDC_CK_PIN_RODANCODE            1249
#define IDC_CK_PIN_RADONLEN             1250
#define IDC_CK_PIN_FIXEDCODE            1251
#define IDC_CK_SIM_BIND                 1252
#define IDC_CK_SIM_BOUNDCODE            1253
#define IDC_STATIC_SIM_BIND             1254
#define IDC_RADIO_SIM_BIND_YES          1255
#define IDC_RADIO_SIM_BIND_NO           1256
#define IDC_COMB_RANDOMPINLEN           1257
#define IDC_EDIT_SIM_BOUNDCODE          1258
#define IDC_HOTHEADER_LIST              1260
#define IDC_LIST_LOCALAREAHEADER        1262
#define IDC_LIST_IPHEADER               1264
#define IDC_LIST_SINGLEHEADER           1264
#define IDC_LIST_CHARGERULE             1264
#define IDC_CHECK_PHONE_AOTULOCK        1265
#define IDC_CHECK_PHONE_CHARGESOUND     1266
#define IDC_CHECK_STARTUP_TIME          1267
#define IDC_CHECK_CHARGE_RATE           1268
#define IDC_COMB_SINGLE_HEADER_TYPE     1274
#define IDC_CHECK_PHONE_ESPUSED         1275
#define IDC_COMB_SINGLE_OPERAT_TYPE     1275
#define IDC_STATIC_TIPS_STATUS          1275
#define IDC_RADIO_PHONE_ESPUSED_ON      1276
#define IDC_RADIO_PHONE_ESPUSED_OFF     1277
#define IDC_DATETIMEPICKER_DATE         1279
#define IDC_DATETIMEPICKER_TIME         1280
#define IDC_PARA_RULE_LIST              1282
#define IDC_RULE_HEADER_LIST            1282
#define IDC_CHECK_QUERY_IPHEADER        1285
#define IDC_CHECK_QUERY_RULEHEADER      1286
#define IDC_SMSCMD_LIST                 1290
#define IDC_RADIO_RULE_APPOINT_ANS      1291
#define IDC_BUTTON_PAGECREATE           1291
#define IDC_EDIT_RULE_APPOINT_ANS       1292
#define IDC_BUTTON_IMPORT               1292
#define IDC_MANAGE_DATA_LIST            1292
#define IDC_BUTTON_EXPORT               1293
#define IDC_BUTTON_MANAGE_IMPORT        1296
#define IDC_BUTTON_IMPORTLACHEADER      1296
#define IDC_BUTTON_EXPORT_LACHEADER     1297
#define IDC_BUTTON_MANAGE_EXPORT        1297
#define IDC_BUTTON_MANAGE_START_UPDATE  1298
#define IDC_BUTTON_DEBUG_READLAC        1298
#define IDC_COMB_SP_OP                  1299
#define IDC_BUTTON_MANAGE_START_UPDATE2 1299
#define IDC_BUTTON_MANAGE_STOP_UPDATE   1299
#define IDC_COMB_SP_SIMPHONELOCK        1300
#define IDC_COMB_SP_LOCKCELL            1301
#define IDC_COMB_SP_LOCKCELLTOTAL       1302
#define IDC_COMB_SP_DIAL                1303
#define IDC_COMB_SP_DISPLAY             1304
#define IDC_CHECK_SP_SMS_TAG            1305
#define IDC_LIST_LOCK_CELL_TABLE        1306
#define IDC_CHECK_LOCK_CELL_TAG         1307
#define IDC_COMB_EX_PARA                1308
#define IDC_COMB_EXPARA_TIPSOUND        1308
#define IDC_COMB_EXPARA_AOTULOCK        1309
#define IDC_COMB_EXPARA_CALLIN          1310
#define IDC_COMB_EXPARA_DIALTIMEOUT     1311
#define IDC_COMB_EXPARA_SPECIALUSE      1312
#define IDC_COMB_EXPARA_AOTULOCKCELL    1313
#define IDC_CHECK_EX_PARA               1314
#define IDC_CHECK_HOT_HEADER            1315
#define IDC_CHECK_FORBID_HEADER         1316
#define IDC_CHECK_LACMOBILEHEADER       1316
#define IDC_CHECK_SINGENHEADER          1317
#define IDC_CHECK_IPRULE                1317
#define IDC_COMB_SKIPTIME               1318
#define IDC_CHECK_CHARGE_LOAD           1319
#define IDC_CHECK_CHARGEHEADER          1320
#define IDC_EDIT_                       1321
#define IDC_EDIT_LOGIN_ID               1321
#define IDC_LIST_IP_QUERY_TABLE         1322
#define IDC_EDIT_LOGIN_ID2              1322
#define IDC_EDIT_LOGIN_ZONECODE         1322
#define IDC_BUTTON_IP_QUERY             1323
#define IDC_BUTTON_IP_QUERY2            1324
#define IDC_BUTTON_QUERY_STOPTHREAD     1324
#define IDC_STATIC_HEADER_QUERY_INFO    1325
#define IDC_STATIC_HEADER_QUERY_INFO_AT 1326
#define IDC_LIST_QUERY_STATUS_SHOW      1326
#define IDC_BUTTON_IP_IMPORT            1327
#define IDC_PROGRESS_ALL_DATA_MANAGE    1327
#define IDC_BUTTON_IP_IMPORT2           1328
#define IDC_BUTTON_IP_EXPORT            1328
#define IDC_BUTTON_DEBUG_READCELL       1329
#define IDC_BUTTON1                     1330
#define IDC_BUTTON_DEBUG_READ_HOTFORBID 1330
#define IDC_BUTTON_DEBUG_READ_RULE_HEADER 1330
#define IDC_BUTTON_DEBUG_RULETAB_READ   1330
#define IDC_BUTTON_DEBUG_READ_IPHEADER  1330
#define IDC_BUTTON_TEXT_CREATE          1330
#define IDC_BUTTON_BIZ_IMPORT_LAC       1330
#define IDC_BUTTON_BIZMANAGE_IMPORT     1330
#define IDC_BUTTON_BIZ_IPHEADER_IMPORT  1330
#define IDC_BUTTON_BIZ_MSGAD_IMPORT     1330
#define IDC_BUTTON_BIZ_INSPECT_IMPORT   1330
#define IDC_BT_CONTENT_SAVESETING       1330
#define IDC_BT_CARTON_PRINT             1330
#define IDC_BUT_PAP_CLEAR_LIST          1330
#define IDC_COMB_FEERULE_YEAR           1331
#define IDC_BUTTON_TEXT_IMPORT_SMS      1331
#define IDC_BUTTON_BIZ_IMPORT_LAC2      1331
#define IDC_BUTTON_BIZ_EXPORT_LAC       1331
#define IDC_BUTTON_BIZMANAGE_EXPORT     1331
#define IDC_BUTTON_BIZ_IPHEADER_EXPORT  1331
#define IDC_BUTTON_BIZ_MSGAD_EXPORT     1331
#define IDC_BUTTON_BIZ_INSPECT_IMPORT2  1331
#define IDC_BUTTON_BIZ_INSPECT_EXPORT   1331
#define IDC_BUT_PAP_QUERY               1331
#define IDC_COMB_FEERULE_MONTH          1332
#define IDC_STATIC_COMM_SET             1332
#define IDC_BUTTON_TEXT_CREATE3         1332
#define IDC_BUTTON_TEXT_EXPORT          1332
#define IDC_BUTTON_BIZMANAGE_START      1332
#define IDC_BUTTON_BIZ_MSGAD_EXPORT2    1332
#define IDC_BUTTON_BIZ_MSGAD_READ       1332
#define IDC_BUT_PAP_CLEAR_LIST2         1332
#define IDC_BUT_PAP_RE_PRINT            1332
#define IDC_COMB_FEERULE_DAY            1333
#define IDC_STATIC_SET_COMM_PORT        1333
#define IDC_BUTTON_BIZMANAGE_INTERMIT   1333
#define IDC_COMB_FEERULE_HOUR           1334
#define IDC_STATIC_SET_COMM_RATE        1334
#define IDC_COMB_FEERULE_YEAR5          1335
#define IDC_COMB_FEERULE_MINUTE         1335
#define IDC_STATIC_SET_USERID           1335
#define IDC_STATIC_SET_ZONECODE         1336
#define IDC_STATIC_X_OUT_RECT           1337
#define IDC_STATIC_FEEHEADER_RECT       1338
#define IDC_EDIT_ZONGBAOCODE            1339
#define IDC_ST_PUB_SP                   1342
#define IDC_ST_PUB_CHARGETABLE          1343
#define IDC_CHECK_SWITCH_0002           1345
#define IDC_COMB_SWITCH_0002            1346
#define IDC_CHECK_SWITCH_0003           1347
#define IDC_COMB_SWITCH_0003            1348
#define IDC_ST_BIZ_SWITCH               1349
#define IDC_CHECK_SWITCH_6000           1350
#define IDC_COMB_SWITCH_6000            1351
#define IDC_CHECK_SWITCH_6001           1352
#define IDC_CHECK_SWITCH_0005           1353
#define IDC_COMB_SWITCH_0005            1354
#define IDC_CHECK_SWITCH_4000           1355
#define IDC_COMB_SWITCH_4000            1356
#define IDC_CHECK_SWITCH_5000           1357
#define IDC_COMB_SWITCH_5000            1358
#define IDC_CHECK_SWITCH_7002           1359
#define IDC_COMB_SWITCH_7002            1360
#define IDC_CHECK_SWITCH_7003           1361
#define IDC_COMB_SWITCH_7003            1362
#define IDC_CHECK_SWITCH_8000           1363
#define IDC_COMB_SWITCH_8000            1364
#define IDC_COMB_SWITCH_6001            1365
#define IDC_COMB_SWITCH_8001            1366
#define IDC_CHECK_SWITCH_8002           1367
#define IDC_COMB_SWITCH_8002            1368
#define IDC_CHECK_SWITCH_8001           1369
#define IDC_CHECK_SWITCH_6005           1370
#define IDC_COMB_SWITCH_6005            1371
#define IDC_CHECK_SWITCH_7000           1372
#define IDC_COMB_SWITCH_7000            1373
#define IDC_EDIT_BIZ_1000               1374
#define IDC_EDIT_BIZ_0004               1375
#define IDC_ST_BIZ_TEXTCMD              1375
#define IDC_CHECK_SWITCH_1000           1376
#define IDC_LIST_TEXT_SMSCMD            1376
#define IDC_CHECK_SWITCH_0004           1377
#define IDC_LIST_BIZ_LAC                1377
#define IDC_EDIT_BIZ_1001               1378
#define IDC_EDIT_BIZ_7001               1378
#define IDC_COMB_BIZ_LAC_MOTHED         1378
#define IDC_CHECK_SWITCH_7001           1379
#define IDC_ST_BIZ_LAC_MOTHED           1379
#define IDC_ST_BIZ_LAC                  1380
#define IDC_ST_BIZ_MANAGE               1381
#define IDC_LIST_BIZ_MANAGE             1382
#define IDC_PROGRESS1                   1383
#define IDC_BIZ_MANAGE_PROGRESS         1383
#define IDC_ST_PUB_MANAGE               1384
#define IDC_LIST2                       1386
#define IDC_LIST_BIZ_LMS                1386
#define IDC_ST_BIZ_LMS                  1387
#define IDC_ST_BIZ_LMS_TIPS             1388
#define IDC_ST_BIZ_LMS_UPDATEMODE       1389
#define IDC_ST_BIZ_IPRULE               1390
#define IDC_LIST_BIZ_IPRULE             1391
#define IDC_CHECK1                      1392
#define IDC_CK_BIZ_IPRULE               1392
#define IDC_CHECK_AG169H                1392
#define IDC_CHECK_PG530_MMI             1392
#define IDC_ST_BIZ_IPRULE_TIPS          1393
#define IDC_ST_BIZ_LOCKCELL             1394
#define IDC_LIST_BIZ_LOCKCELL           1395
#define IDC_ST_                         1396
#define IDC_ST_CONTENT_TEMPLET          1396
#define IDC_ST_IPHEADER                 1397
#define IDC_LIST_BIZ_IPHEADER           1398
#define IDC_COMB_BIZ_IPHEADER_OP        1399
#define IDC_ST_BIZ_IPHEADER_OP          1400
#define IDC_ST_BIZ_SMSAD                1401
#define IDC_BIZ_SMSAD_LIST              1402
#define IDC_ST_BIZ_INSPECT              1403
#define IDC_BIZ_INSPECT_LIST            1404
#define IDC_ST_BIZ_LOCKCELL_TIPS        1405
#define IDC_COMBO1                      1406
#define IDC_COMB_BIZ_LOCKCELL_TOTAL     1406
#define IDC_COMBO1_IMEI_MODEL           1406
#define IDC_COMB_CARTON_MODEL           1406
#define IDC_ST_IMEI_MODEL               1407
#define IDC_COMB_CARTON_QUANTITY        1407
#define IDC_ST_IMEI_CONTENTS            1408
#define IDC_ET_IMEI_MAINSET             1409
#define IDC_ET_IMEI_HANDSET             1410
#define IDC_ET_IMEI_ANT                 1411
#define IDC_ET_IMEI_BAT                 1412
#define IDC_ET_IMEI_USER                1413
#define IDC_ST_IMEI_MODEL2              1414
#define IDC_COMBO1_IMEI_COLOR           1415
#define IDC_COMB_CONTENT_YEAR           1416
#define IDC_ST_IMEI                     1417
#define IDC_ST_CARTON_MODEL             1417
#define IDC_ET_IMEI_IMEI                1418
#define IDC_ST_CARTON_CTBOXID           1418
#define IDC_ST_IMEI2                    1419
#define IDC_EDIT_CARTON_CTID            1419
#define IDC_ET_IMEI_SNO                 1420
#define IDC_ST_CARTON_COUNT             1420
#define IDC_ET_IMEI_ADA                 1421
#define IDC_ST_CARTON_IMEI              1421
#define IDC_COMBO3                      1422
#define IDC_COMB_CONTENT_MON            1422
#define IDC_ST_CARTON_SNO               1422
#define IDC_EDIT_CARTON_IMEI            1423
#define IDC_EDIT_CARTON_SNO             1424
#define IDC_CARTON_LIST                 1425
#define IDC_ST_CARTON_REPRINT           1426
#define IDC_EDIT_CARTON_REPRINT         1427
#define IDC_ED_PAP_IMEI                 1427
#define IDC_ST_CARTON_ORDER             1428
#define IDC_EDIT_CARTON_ORDER           1429
#define IDC_EDIT_QCS_BOXID              1429
#define IDC_ST_CARTON_AREA              1430
#define IDC_EDIT_QCS_MODEL              1430
#define IDC_EDIT_CARTON_AREA            1431
#define IDC_EDIT_QCS_EDITION            1431
#define IDC_ST_CARTON_AG169H            1432
#define IDC_EDIT_QCS_REQ                1432
#define IDC_ED_PAP_BOXID                1433
#define IDC_EDIT_QCS_OFM                1433
#define IDC_ED_PAP_SYMBOL               1434
#define IDC_EDIT_QCS_OFM2               1434
#define IDC_EDIT_QCS_DATE               1434
#define IDC_ED_PAP_MODEL                1435
#define IDC_ED_PAP_COLOR                1436
#define IDC_ED_PAP_WEIGHT               1437
#define IDC_ED_PAP_ADDONS               1438
#define IDC_ED_PAP_EDITION              1439
#define IDC_ED_PAP_MESTATE              1440
#define IDC_ED_PAP_AMOUNT               1441
#define IDC_ED_PAP_PESTATE              1442
#define IDC_ED_PAP_REQ                  1443
#define IDC_CUSTOM_PHONEIMEI_PACK       1444
#define IDC_ED_PAP_OFORM                1445

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1430
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
